---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vault.yml
  gather_facts: false
  serial: 1
  roles:
    # - role: '/home/snow/Ansible_WinRm/VM_Config/Linux_roles/Test_role'
    # - role: '/home/snow/Ansible_WinRm/VM_Config/windows_roles'
    #- role: '/home/snow/Ansible_WinRm/VM_Config/Linux_roles/Nginx_role'
    - role: '/home/snow/Ansible_WinRm/VM_Config/Linux_roles/Join_ad'